### ISSUE TITLE
Issues running demo

### ISSUE THREAD

**Issue by hai-h-nguyen** [NVlabs/GraspGen#12]
Hi, thanks for the code. However, I got this when running the demo in docker.

```
 File "/code/scripts/demo_scene_pc.py", line 19, in <module>
    from grasp_gen.grasp_server import GraspGenSampler, load_grasp_cfg
  File "/code/grasp_gen/grasp_server.py", line 19, in <module>
    from grasp_gen.models.grasp_gen import GraspGen
  File "/code/grasp_gen/models/grasp_gen.py", line 16, in <module>
    from grasp_gen.models.discriminator import GraspGenDiscriminator
  File "/code/grasp_gen/models/discriminator.py", line 28, in <module>
    from grasp_gen.models.ptv3.ptv3 import PointTransformerV3
  File "/code/grasp_gen/models/ptv3/ptv3.py", line 16, in <module>
    from timm.models.layers import DropPath
  File "/usr/local/lib/python3.10/dist-packages/timm/__init__.py", line 8, in <module>
    from .models import (
  File "/usr/local/lib/python3.10/dist-packages/timm/models/__init__.py", line 1, in <module>
    from .beit import *
  File "/usr/local/lib/python3.10/dist-packages/timm/models/beit.py", line 52, in <module>
    from ._builder import build_model_with_cfg
  File "/usr/local/lib/python3.10/dist-packages/timm/models/_builder.py", line 13, in <module>
    from timm.models._helpers import load_state_dict
  File "/usr/local/lib/python3.10/dist-packages/timm/models/_helpers.py", line 11, in <module>
    import safetensors.torch
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 439, in <module>
    torch.uint64: 8,
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1833, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'uint64'
```

It seems that `safetensor` uses torch.uint64 which requires higher version of PyTorch. How to fix this?

**Comment by adithyamurali** [comment]
Hi @hai-h-nguyen are you using this [dockerfile](https://github.com/NVlabs/GraspGen/blob/main/docker/graspgen_cuda121.dockerfile) specified in the [default build script](https://github.com/NVlabs/GraspGen/blob/main/docker/build.sh#L2). This should use pytorch version `2.1.0+cu121`.

The demo scripts have been tested with this version and should work on the latest `cu12.8` version as well (barring this [issue](https://github.com/NVlabs/GraspGen/tree/main?tab=readme-ov-file#future-features-on-the-roadmap)). 

What version of pytorch and cuda do you have in the above environment?
